In [1]:
import os 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px

In [2]:
current_directory = os.getcwd()
df = pd.read_csv(f'{current_directory}\\Retail_StoreDataset.csv')
df.head()

,Transaction_ID,Store_Region,Product_Category,Payment_Method,Customer_Type,Unit_Price,Items_Sold,Gross_Amount,Discount_Percent,Discount_Amount,Net_Sales_Amount,Average_Price_Per_Item,Effective_Discount_Per_Item
0,TXN1000,East,Grocery,Cash,New,321.44,9.0,2892.96,9.13,264.13,2628.83,292.09,29.35
1,TXN1001,West,Furniture,Wallet,Member,873.53,4.0,3494.12,17.01,594.35,2899.77,724.94,148.59
2,TXN1002,North,Apparel,Wallet,Guest,188.47,3.0,565.41,9.92,56.09,509.32,169.77,18.70
3,TXN1003,South,Furniture,Wallet,Guest,326.10,11.0,3587.10,10.01,359.07,3228.03,293.46,32.64
4,TXN1004,North,Electronics,Credit Card,New,356.04,17.0,6052.68,4.36,263.90,5788.78,340.52,15.52

In [3]:
df.describe()

,Unit_Price,Items_Sold,Gross_Amount,Discount_Percent,Discount_Amount,Net_Sales_Amount,Average_Price_Per_Item,Effective_Discount_Per_Item
count,5609.000000,5609.000000,5492.000000,5536.000000,5448.000000,5497.000000,5411.000000,5387.00000
mean,545.865113,9.699055,5356.970481,14.622968,774.255921,4560.112339,463.764432,81.92517
std,272.010358,5.646474,4339.285388,8.265091,839.326863,3787.546846,237.498478,65.21121
min,54.870000,1.000000,90.550000,0.280000,8.490000,77.300000,44.800000,0.57000
25%,309.340000,5.000000,1856.040000,7.750000,144.400000,1524.980000,269.740000,24.62000
50%,564.310000,10.000000,4024.150000,13.640000,466.900000,3259.750000,459.990000,69.26000
75%,765.530000,15.000000,8136.090000,21.820000,1072.290000,7281.840000,664.190000,126.76000
max,989.050000,19.000000,17353.270000,29.760000,4426.400000,16008.390000,929.380000,260.38000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5627 entries, 0 to 5626
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Transaction_ID               5627 non-null   object
 1   Store_Region                 5627 non-null   object
 2   Product_Category             5627 non-null   object
 3   Payment_Method               5627 non-null   object
 4   Customer_Type                5622 non-null   object
 5   Unit_Price                   5609 non-null   float64
 6   Items_Sold                   5609 non-null   float64
 7   Gross_Amount                 5492 non-null   float64
 8   Discount_Percent             5536 non-null   float64
 9   Discount_Amount              5448 non-null   float64
 10  Net_Sales_Amount             5497 non-null   float64
 11  Average_Price_Per_Item       5411 non-null   float64
 12  Effective_Discount_Per_Item  5387 non-null   float64
dtypes: float64(8), object(5)
memory usage: 571.6+ KB

In [5]:
df.isnull().sum()

Transaction_ID                   0
Store_Region                     0
Product_Category                 0
Payment_Method                   0
Customer_Type                    5
Unit_Price                      18
Items_Sold                      18
Gross_Amount                   135
Discount_Percent                91
Discount_Amount                179
Net_Sales_Amount               130
Average_Price_Per_Item         216
Effective_Discount_Per_Item    240
dtype: int64

In [6]:
df.dropna(inplace=True)

In [7]:
df.describe()

,Unit_Price,Items_Sold,Gross_Amount,Discount_Percent,Discount_Amount,Net_Sales_Amount,Average_Price_Per_Item,Effective_Discount_Per_Item
count,4796.000000,4796.000000,4796.000000,4796.000000,4796.000000,4796.000000,4796.000000,4796.000000
mean,543.277281,9.726439,5330.202869,14.576241,773.137934,4557.064935,462.677927,82.370555
std,274.322884,5.566830,4319.809419,8.132779,849.980191,3703.771308,237.431504,65.561650
min,54.870000,1.000000,90.550000,0.280000,8.490000,77.300000,44.800000,0.570000
25%,293.040000,5.000000,1856.040000,7.780000,144.400000,1534.400000,257.310000,24.620000
50%,564.310000,10.000000,3877.880000,13.560000,466.900000,3268.060000,460.850000,69.260000
75%,765.620000,15.000000,8136.090000,21.665000,1043.400000,7439.420000,664.190000,127.540000
max,989.050000,19.000000,17353.270000,29.760000,4426.400000,16008.390000,910.770000,260.380000

In [8]:
df.to_csv('cleaned_retail_sales_data.csv', index=False)